"""Service-specific marketing pages using the approved homepage visual system."""
def make_pages(ctx):
    e, icon, btn, photo, faq, plans, callout = [ctx[x] for x in ('e','icon','btn','photo','faq','plans','callout')]
    config, FAQ = ctx['CONFIG'], ctx['FAQ']
    originals = {name:ctx[name] for name in ('hosting','domains','email','design_content','support','contact','about','ssl','account','policies','checkout','domain_search')}
    def rest(name): return originals[name]().split('</section>',1)[1]
    def hero(kind,kicker,title,text,actions,visual,extra=''):
        return f'''<section class="service-hero service-{kind}"><div class="wrap service-hero-grid"><div class="service-copy"><p class="eyebrow">{e(kicker)}</p><h1>{title}</h1><p class="lead">{text}</p><div class="actions">{actions}</div>{extra}</div><div class="service-art" data-tilt aria-hidden="true"><div class="service-halo"></div><div class="service-scene">{visual}</div></div></div></section>'''
    def guide(label='Build my setup',goal=''):
        return btn(label,'setup.html'+('?goal='+goal if goal else ''),True)
    def server():
        return '<div class="rack-scene"><div class="rack-label">A HOME FOR YOUR WEBSITE</div>'+''.join(f'<div class="rack-unit"><span class="rack-light"></span><strong>{label}</strong><div class="rack-slots"><i></i><i></i><i></i></div></div>' for label in ['Your website files','Your business email','Your next project'])+'<div class="rack-base"></div><div class="scene-chip chip-copper">15–60 GB <span>NVMe storage</span></div><div class="scene-chip chip-mint">cPanel <span>You’re in control</span></div></div>'
    def domain_visual():
        return f'<div class="domain-world"><div class="world-ring"></div><div class="world-core">{icon("domain")}</div><div class="address-slab"><small>YOUR ADDRESS ONLINE</small><strong>yourbusiness<span>.co.za</span></strong></div><div class="scene-chip chip-copper">.com <span>Go beyond borders</span></div><div class="scene-chip chip-mint">.co.za <span>Made for South Africa</span></div></div>'
    def mail_visual():
        return f'<div class="mail-scene"><div class="mail-sheet"><span class="sheet-label">FROM YOUR BUSINESS</span><div class="mail-identity"><div class="mail-avatar">M</div><div><strong>Your Business</strong><span>hello@yourbusiness.co.za</span></div></div><h3>Let’s talk about<br>your next project.</h3><p>Thanks for your enquiry.<br>Here’s how we can help.</p><div class="mail-signature">Your name.<br><b>Your business.</b></div></div><div class="scene-chip chip-mint">sales@ <span>One domain. Your team.</span></div><div class="scene-chip chip-copper">accounts@ <span>A professional reply</span></div></div>'
    def website_visual():
        return f'<div class="design-scene"><div class="design-browser"><div class="stack-bar"><i></i><i></i><i></i><span>YOUR BUSINESS</span></div>{photo("business-workspace", "", True)}<div class="design-browser-copy"><small>SHOW WHAT YOU DO</small><strong>Your work.<br>Worth discovering.</strong><span>Get in touch ↗</span></div></div><div class="design-phone"><div></div><small>YOUR BUSINESS</small><strong>Built for<br>every screen.</strong><span>Let’s talk ↗</span></div><div class="scene-chip chip-mint">4 or 6 pages <span>A clear place to start</span></div></div>'
    def security_visual():
        return f'<div class="ssl-scene"><div class="ssl-shield">{icon("lock")}</div><div class="ssl-url"><span>https://</span><strong>yourbusiness.co.za</strong></div><div class="ssl-path"><span>Your visitor</span><i></i><span>Your website</span></div><div class="scene-chip chip-mint">Encrypted connection <span>Protect data in transit</span></div></div>'
    def support_visual():
        return f'<div class="help-scene"><div class="help-sheet"><div class="help-icon">{icon("support")}</div><small>LET’S FIND THE NEXT STEP</small><h3>Website?<br>Email?<br>Domain?</h3><p>Tell us what happened.<br>We’ll work through it with you.</p></div><div class="scene-chip chip-mint">A clear answer <span>Start with the right details</span></div></div>'
    def contact_visual():
        return f'<div class="contact-scene"><div class="contact-slab"><span class="contact-mono">M<span>HOSTING</span></span><small>BASED IN PRETORIA</small><strong>Let’s build<br>your next step.</strong><p>{e(config["email"])}</p></div><div class="scene-chip chip-copper">Your business <span>Our starting point</span></div></div>'
    def hosting():
        return hero('hosting','Web hosting','A home for your site.<br><span>Room for your next step.</span>','Website files and business email, together. From <strong>R59 a month</strong> with NVMe storage, LiteSpeed and cPanel.',btn('Compare hosting','#hosting-plans',True)+btn('Guide me','setup.html'),server(),'<ul class="hero-proof"><li>15–60 GB storage</li><li>2–5 websites</li><li>Email accounts included</li></ul>')+rest('hosting')
    def domains():
        original_rest=rest('domains')
        original_rest=original_rest.replace(ctx['domain_panel'](),'<div class="domain-explain card"><p class="eyebrow">One name. Two uses.</p><h3>yourbusiness.co.za</h3><p>Your website address.</p><h3>hello@yourbusiness.co.za</h3><p>Your business email address.</p><p>The domain is your name. Hosting stores your website and email.</p>'+guide('Help me choose','domain')+'</div>')
        return hero('domains','Domain names','Your name.<br><span>Your place online.</span>','Choose an address people can remember. Connect it to your website and email, or keep the domain you already own.',btn('I already have a domain','domain-search.html?mode=transfer'),domain_visual(),ctx['domain_form']())+original_rest
    def email():
        return hero('email','Business email','Your name.<br><span>In every inbox.</span>','Send quotes, invoices and replies from your business domain. Give your team addresses that customers recognise.',guide('Plan my business email','email')+btn('Compare hosting','hosting.html#hosting-plans'),mail_visual(),'<ul class="hero-proof"><li>Email accounts included in hosting</li><li>Help planning a move</li></ul>')+rest('email')
    def design_content():
        return hero('websites','Website design','Show your work.<br><span>Win the next enquiry.</span>','Make your services easy to understand and your business easy to contact. Responsive business websites from <strong>R2 599 once-off</strong>.',btn('Compare website packages','#design-packages',True)+btn('Guide my setup','setup.html?goal=design'),website_visual(),'<ul class="hero-proof"><li>4- and 6-page packages</li><li>Your content integrated</li><li>50% deposit</li></ul>')+rest('design_content')
    def design(): return design_content()+ctx['portfolio']()
    def ssl():
        coverage = ctx['card']('One website','Check coverage for your website name and the hostnames it uses.','lock','Guide my SSL','setup.html?goal=ssl')+ctx['card']('Several subdomains','A wildcard may suit first-level subdomains such as shop.yourbusiness.co.za.','domain','Plan my coverage','setup.html?goal=ssl')+ctx['card']('Different domains','Discuss a multi-domain certificate when your sites use different domain names.','hosting','Check what I need','setup.html?goal=ssl')
        return hero('ssl','SSL & HTTPS','Protect the connection.<br><span>Keep the conversation private.</span>','HTTPS encrypts data between a visitor and your website. Start by checking your existing certificate before choosing extra coverage.',guide('Help me choose SSL','ssl')+btn('Ask about a browser warning','contact.html?service=ssl'),security_visual())+f'<section class="section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">The right coverage</p><h2>One website or several?<br>Let’s check.</h2></div><p>SSL protects the connection. Website software still needs updates, backups and secure access.</p></div><div class="cards">{coverage}</div></div></section>'+originals['ssl']().split('<section class="section section-tint">',1)[-1].join(['<section class="section section-tint">',''])
    def support():
        return hero('support','Help & support','Less guessing.<br><span>Let’s get it sorted.</span>','For an existing service, tell us your domain, what you were trying to do and any error message. Never send passwords.',btn('Find an answer','#common-questions',True)+btn('Email support','mailto:'+config['email']+'?subject=Existing%20service%20support'),support_visual(),'<p class="service-direct">Use email for service support.</p>')+rest('support')
    def contact():
        form='<section class="section section-tint">'+originals['contact']().split('<section class="section section-tint">',1)[1]
        return hero('contact','Contact Mumatec','A real conversation.<br><span>A better next step.</span>','Starting, moving or fixing something? Tell us where you are now and what you want to do next.',btn('Tell us what you need','#enquiry',True)+btn('Guide my setup','setup.html'),contact_visual(),f'<p class="service-direct"><a href="mailto:{e(config["email"])}">{e(config["email"])}</a></p>')+form
    def about():
        visual=f'<div class="about-scene">{photo("pretoria-business-hero","",True)}<div class="about-caption"><small>LOCAL BUSINESS. REAL POSSIBILITIES.</small><strong>Your next chapter<br>starts with you.</strong></div><div class="scene-chip chip-mint">Pretoria <span>South Africa</span></div></div>'
        cards=ctx['card']('Choose what fits','Start with the services you need today. Keep the choices and costs clear.','hosting','Build my setup','setup.html')+ctx['card']('Bring what you have','Keep your domain, discuss your existing website and plan any email move.','domain','Plan my move','setup.html?goal=move')+ctx['card']('Speak to us','A hosting choice should make sense to you. Ask us about the setup before you decide.','support','Talk to Mumatec','contact.html')
        return hero('about','About Mumatec','Local businesses.<br><span>Bigger possibilities.</span>','Mumatec helps South African businesses get online with hosting, domains, business email and website design. Based in Pretoria, focused on your next step.',guide()+btn('Speak to us','contact.html'),visual)+f'<section class="section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">Built around your business</p><h2>Your idea deserves<br>a place online.</h2></div><p>You don’t need every service on day one. We help you put the right pieces together.</p></div><div class="cards">{cards}</div></div></section>'+callout('Let’s make the next step clear.','Choose your goal. We’ll guide you through what you need.','Build my setup','setup.html')
    def account():
        return hero('account','Customer account','Your service.<br><span>Help within reach.</span>','Need help with an existing account or service? Contact Mumatec while the new customer portal is being prepared.',btn('Email account support','mailto:'+config['email']+'?subject=Account%20support',True)+btn('Find service help','support.html'),support_visual())+rest('account')
    def policies():
        return hero('policies','Pricing & service details','Clear choices.<br><span>No hidden assumptions.</span>','Know how billing works, what each service includes and which costs are separate before setting up your business.',btn('Compare hosting','hosting.html#hosting-plans',True)+btn('Ask about service terms','contact.html'),contact_visual())+rest('policies')
    return locals() | {'design':design}
