"""Accessible, local-only guided setup shell."""
def render_setup(ctx):
    icon,e=ctx['icon'],ctx['e']
    def choice(name,value,title,detail='',symbol=None,checked=False):
        return f'<label class="setup-choice"><input type="radio" name="{name}" value="{value}"'+(' checked' if checked else '')+f'><span class="choice-surface">'+(icon(symbol) if symbol else '')+f'<span><strong>{title}</strong>'+ (f'<small>{detail}</small>' if detail else '')+'</span><span class="choice-check" aria-hidden="true"></span></span></label>'
    def panel(key,title,hint,content):
        return f'<fieldset class="setup-panel" data-step="{key}" hidden><legend class="setup-question" tabindex="-1">{title}</legend><p class="setup-hint">{hint}</p>{content}</fieldset>'
    goals=''.join(choice('goal',*args) for args in [
        ('start','Get my business online','A website, email and the right place to host them.','hosting'),
        ('move','Move my website','Keep what works. Plan the hosting and email move.','domain'),
        ('email','Set up business email','Email using my own business name.','email'),
        ('domain','Get a domain name','Just the address, without adding other services.','domain'),
        ('design','Have a website built','Choose design, with or without new hosting.','design'),
        ('ssl','Check SSL for my website','HTTPS coverage for a site I already have.','lock')])
    website=''.join(choice('website',*args) for args in [
        ('build','I’d like Mumatec to build it','Choose a business website package or discuss a custom site.','design'),
        ('existing','I already have a website','Keep my website and help with the setup or move.','domain'),
        ('self','I’ll build it myself','I only need the services around my website.','hosting'),
        ('later','I’ll decide on a website later','Start with my domain or hosting.','support')])
    design=''.join(choice('design',p['id'],e(p['name'])+f' · R{ctx["money"](p["price"])} once-off',f'Up to {p["pages"]} pages. Responsive design. 50% deposit.','design') for p in ctx['CONFIG']['designPlans'])+choice('design','custom','Custom website or online shop','Discuss pages, features and budget. Price by quote.','design')
    hosting=''.join(choice('hosting',*args) for args in [
        ('mumatec','Host with Mumatec','Website and email space. Choose a package next.','hosting'),
        ('existing','I already have hosting','Keep my current hosting; help with the other services.','domain'),
        ('quote','Help me check what I need','Discuss an email-only setup or hosting requirements first.','support')])
    site_options=''.join(f'<option value="{v}">{t}</option>' for v,t in [('','Choose the number'),('1','1 website'),('2','2 websites'),('3','3 websites'),('4','4 websites'),('5','5 websites'),('6+','6 or more websites')])
    capacity=''.join(choice('storage',v,t,d) for v,t,d in [('15','Up to 15 GB','A smaller website and everyday email.'),('30','Up to 30 GB','More website files or stored email.'),('60','Up to 60 GB','Several sites or a larger shared mailbox footprint.'),('over','More than 60 GB','We’ll discuss a suitable setup.'),('unsure','I’m not sure','Suggest a starting point; confirm my storage first.')])
    package=''.join(choice('plan',p['id'],e(p['name']),f'{p["storage"]} GB shared storage · {p["websites"]} websites · R{p["monthly"]}/month','hosting') for p in ctx['CONFIG']['hostingPlans'])
    domain=''.join(choice('domainNeed',*args) for args in [('new','I need a new domain','Choose a business name and domain ending.','domain'),('existing','I already own one','Use my domain without paying to register it again.','domain'),('later','I’ll choose it later','Keep domain registration out of this estimate.','support')])
    extensions=''.join(choice('extension',d['extension'],'.'+d['extension']+f' · R{ctx["money"](d["price"])} / year','Registration price guide.',checked=i==0) for i,d in enumerate(ctx['CONFIG']['domainExamples']))
    email=''.join(choice('email',*args) for args in [('yes','Yes, use my business domain','Email accounts are included when I select hosting.','email'),('existing','Keep my current email provider','Plan the domain settings around the email I already use.','domain'),('no','I don’t need email yet','Leave mailbox setup out for now.','support')])
    ssl=''.join(choice('ssl',v,t,d,'lock',v=='check') for v,t,d in [('check','Check my existing or hosting coverage first','Recommended starting point. No extra certificate is added automatically.'),('single','I need coverage for one website','Confirm the website names, current coverage and price.'),('wildcard','I use several subdomains','For names such as shop.yourbusiness.co.za at the same subdomain level.'),('multi','I use different domain names','Discuss coverage for several domain names.'),('existing','My SSL is already managed','Keep it. Confirm it still covers the setup.')])
    panels=[
        panel('goal','What would you like to do?','Choose the starting point that matches your business. We’ll only ask about services you might need.',f'<div class="setup-options">{goals}</div>'),
        panel('website','Do you need a website built?','A website is what customers see: your services, work and contact details.',f'<div class="setup-options">{website}</div><div data-design-options hidden><h2 class="setup-subheading">Choose your website package</h2><div class="setup-options one-column">{design}</div><p class="input-help">Hosting, a domain and ongoing maintenance are separate. We confirm the scope before work begins.</p></div>'),
        panel('hosting','Where will your website or email live?','Hosting provides storage for website files and mailboxes. You can choose Mumatec or keep hosting you already have.',f'<div class="setup-options one-column">{hosting}</div>'),
        panel('capacity','How much room do you need?','Storage is shared by website files and email. Website count and storage both affect which plan fits.',f'<label for="setup-sites">How many websites will you host?</label><select id="setup-sites" name="sites" aria-describedby="setup-error">{site_options}</select><h2 class="setup-subheading">How much shared storage?</h2><div class="setup-options">{capacity}</div><p class="input-help">If you already have hosting, check its disk usage. If you’re unsure, we’ll confirm the space before setup.</p>'),
        panel('package','Choose your hosting package','We’ll suggest the lowest-priced package that meets the website count and storage you selected. You can choose more room.',f'<p class="setup-recommendation" data-recommendation role="status"></p><div class="setup-options one-column">{package}</div><fieldset class="setup-billing"><legend>How would you like to pay?</legend><div class="setup-options">'+choice('cycle','monthly','Monthly','Pay for hosting each month.',checked=True)+choice('cycle','yearly','Yearly','Pay the full year upfront and save.')+'</div></fieldset>'),
        panel('domain','What’s your business address online?','A domain is the name people type, such as yourbusiness.co.za. It can also be used for your email.',f'<div class="setup-options one-column">{domain}</div><div data-domain-fields hidden><label for="setup-domain">Your domain name</label><input id="setup-domain" name="domain" maxlength="253" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="yourbusiness.co.za" aria-describedby="setup-domain-help setup-error"><p id="setup-domain-help" class="input-help">Enter your existing domain, or the name you’d like to register.</p><div data-domain-action hidden><h2 class="setup-subheading">Where should it be managed?</h2><div class="setup-options">{choice('domainAction','keep','Keep my registrar','Connect the domain using DNS settings.',checked=True)}{choice('domainAction','transfer','Discuss a transfer','Confirm eligibility, fees and timing first.')}</div></div><div data-extension-options hidden><h2 class="setup-subheading">Choose a domain ending</h2><div class="setup-options">{extensions}</div><p class="input-help">This guide does not check availability. Current registration and renewal prices are confirmed before ordering.</p></div></div>'),
        panel('email','Would you like business email?','Use an address such as hello@yourbusiness.co.za. Keep an existing provider if it already works for you.',f'<div class="setup-options one-column">{email}</div><p class="input-help" data-email-note>Email accounts and website files share the hosting storage you choose. Separate email services need a quote.</p>'),
        panel('ssl','How should we handle HTTPS?','SSL/TLS protects data travelling between visitors and your website. Check what you already have before adding a certificate.',f'<div class="setup-options one-column">{ssl}</div><p class="input-help">Coverage, installation and renewal costs are confirmed if a new certificate is needed. HTTPS does not replace website updates or backups.</p>'),
        panel('review','Your business setup, together.','Review each service and its cost. You can change a choice before taking the next step.','<div data-setup-review></div><div class="setup-final-actions"><a class="btn btn-primary" data-setup-email>Open setup enquiry in my email app ↗</a><button class="btn" type="button" data-setup-save disabled>Save my setup</button></div><p class="input-help">Nothing is ordered or paid here. Mumatec confirms domain availability, applicable taxes, service scope and renewal terms. You review and send the enquiry in your own email app.</p>')
    ]
    return '''<section class="setup-intro"><div class="wrap"><a class="setup-return" href="hosting.html">← Compare hosting</a><p class="eyebrow">Let’s choose it together</p><h1>Build your business setup.</h1><p>One choice at a time. Understand what you need, then bring it all together.</p></div></section><section class="setup-section"><div class="wrap"><noscript><div class="card"><h2>Choose your services</h2><p>The step-by-step guide needs JavaScript. You can still compare services or ask Mumatec for help.</p><div class="actions"><a class="btn" href="hosting.html">Hosting</a><a class="btn" href="domains.html">Domains</a><a class="btn" href="websites.html">Website packages</a><a class="btn" href="contact.html">Get help</a></div></div></noscript><div data-setup hidden><div class="setup-progress"><p data-step-count aria-live="polite"></p><progress data-step-progress max="9" value="1" aria-label="Setup progress"></progress><button class="setup-restart" data-setup-restart type="button" disabled>Start again</button></div><nav class="setup-step-nav" data-step-nav aria-label="Setup steps"></nav><div class="setup-layout"><form class="setup-form" data-setup-form novalidate><div class="setup-direction" data-setup-direction><span aria-hidden="true">↓</span><p>Start here: choose what you need below.</p></div>'''+''.join(panels)+'''<p class="setup-error" id="setup-error" role="alert" hidden></p><div class="setup-controls"><button class="btn" data-setup-back type="button" disabled>← Back</button><button class="btn btn-primary" data-setup-next type="submit" disabled>Continue →</button></div></form><aside class="setup-aside" aria-label="Your setup guide"><figure class="setup-explainer" data-setup-explainer></figure><div class="setup-snapshot"><h2>Your setup so far</h2><div data-setup-snapshot></div></div><p class="setup-help">Need a hand? <a href="contact.html">Talk to Mumatec ↗</a></p></aside></div></div></div></section>'''
