const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'../public');let checks=0;
function page(query='',stored){const dom=new JSDOM(fs.readFileSync(root+'/setup.html','utf8'),{url:'https://review.example/setup.html'+query,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.HTMLElement.prototype.scrollIntoView=function(){};w.fetch=()=>{throw Error('No network allowed')};if(stored)w.sessionStorage.setItem('mumatec-setup-v2',stored);for(const file of ['site.js','setup.js'])w.eval(fs.readFileSync(root+'/assets/'+file,'utf8'));return w;}
function eq(a,b){assert.deepEqual(a,b);checks++}function ok(a){assert.ok(a);checks++}function current(w){return w.document.querySelector('.setup-panel:not([hidden])').dataset.step}function choose(w,name,value){const el=w.document.querySelector('[name="'+name+'"][value="'+value+'"]')||w.document.querySelector('[name="'+name+'"]');if(el.tagName==='SELECT')el.value=value;else el.checked=true;el.dispatchEvent(new w.Event('change',{bubbles:true}));}function text(w,v){const el=w.document.querySelector('[name=domain]');el.value=v;el.dispatchEvent(new w.Event('input',{bubbles:true}));}function next(w){w.document.querySelector('form[data-setup-form]').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
let w=page();next(w);eq(current(w),'goal');ok(!w.document.querySelector('#setup-error').hidden);choose(w,'goal','domain');next(w);eq(current(w),'hosting');choose(w,'hosting','mumatec');next(w);choose(w,'sites','1');choose(w,'storage','15');next(w);next(w);eq(current(w),'domain');choose(w,'domainNeed','new');text(w,'Acme');next(w);eq(current(w),'review');const review=()=>w.document.querySelector('[data-setup-review]').textContent;ok(review().includes('acme.co.za'));ok(review().includes('Hosting'));ok(review().match(/R90[.,]50/));ok(w.document.querySelector('[data-setup-email]').href.startsWith('mailto:'));w.close();
w=page();choose(w,'goal','start');next(w);choose(w,'website','build');next(w);eq(current(w),'website');choose(w,'design','business');next(w);eq(current(w),'hosting');choose(w,'hosting','mumatec');next(w);choose(w,'sites','3');choose(w,'storage','30');next(w);eq(current(w),'package');eq(w.document.querySelector('[name=plan]:checked').value,'start-up-30');ok(w.document.querySelector('[name=plan][value=start-up-15]').disabled);choose(w,'cycle','yearly');next(w);choose(w,'domainNeed','new');text(w,'acme.com');next(w);choose(w,'email','yes');next(w);eq(current(w),'ssl');next(w);eq(current(w),'review');ok(review().includes('R3'));ok(review().includes('R1'));ok(review().includes('Check existing coverage first'));ok(!review().includes('undefined'));ok(decodeURIComponent(w.document.querySelector('[data-setup-email]').href).includes('acme.com'));const saved=w.sessionStorage.getItem('mumatec-setup-v2');w.close();w=page('',saved);eq(current(w),'review');w.document.querySelector('[aria-label="Change Website"]').click();eq(current(w),'website');choose(w,'website','existing');next(w);ok(!review().includes('Website design'));w.close();
w=page('?goal=ssl');next(w);eq(current(w),'domain');eq(w.document.querySelector('[name=domainNeed]:checked').value,'existing');text(w,'bad space');next(w);eq(current(w),'domain');ok(w.document.querySelector('[name=domain]').getAttribute('aria-invalid')==='true');text(w,'acme.co.za');next(w);eq(current(w),'ssl');choose(w,'ssl','wildcard');next(w);ok(review().includes('wildcard'));ok(!review().includes('Annual services'));w.close();
w=page();choose(w,'goal','email');next(w);choose(w,'hosting','mumatec');next(w);choose(w,'sites','6+');choose(w,'storage','over');next(w);eq(current(w),'domain');choose(w,'domainNeed','existing');text(w,'acme.co.za');choose(w,'domainAction','transfer');next(w);eq(current(w),'review');ok(review().includes('quote needed'));ok(review().includes('Request a transfer'));ok(!review().includes('SSL / HTTPS'));w.close();
w=page('',JSON.stringify({version:2,current:'review',answers:{goal:'start',domain:'<script>alert(1)</script>'}}));eq(current(w),'website');eq(w.document.querySelectorAll('script:not([src])').length,1);w.close();w=page('?goal=design');next(w);choose(w,'website','build');choose(w,'design','pro-start-up');next(w);choose(w,'hosting','existing');next(w);eq(current(w),'domain');ok(w.document.querySelector('[name=domainNeed][value=new]').disabled);choose(w,'domainNeed','new');text(w,'acme.co.za');next(w);eq(current(w),'domain');choose(w,'domainNeed','existing');next(w);choose(w,'email','existing');next(w);next(w);eq(current(w),'review');ok(review().includes('External-host setup'));ok(review().includes('R300'));ok(review().match(/R2[\s,]899/));w.document.querySelector('[aria-label="Change Hosting"]').click();choose(w,'hosting','mumatec');next(w);ok(!review().includes('External-host setup'));w.close();
for(const file of fs.readdirSync(root).filter(f=>f.endsWith('.html'))){ok(!/tel:|067\s*735\s*4792|27677354792/.test(fs.readFileSync(root+'/'+file,'utf8')));}
console.log(checks+' guided setup and privacy assertions passed.');
